Models/Service.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace CodeVoyage.Models
{
    public class Service
	{
        public int Id { get; set; }
        [Display(Name = "Nom du Service")]
        [Required(ErrorMessage = "Le nom du service doit être rempli.")]
        public string nomService { get; set; }

        [Display(Name = "Type de Service")]
        public TypeService TypeService { get; set; }
        [Display(Name = "Capacité")]

        public int Capacite { get; set; }
        [Display(Name = "Date de début")]
        public DateTime DateDeb { get; set; }
        [Display(Name = "Date de fin")]
        public DateTime DateFin { get; set; }
        [Display(Name = "Prix en euros")]
        public double Prix { get; set; }

    }
}

Controllers/EvenementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CodeVoyage.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CodeVoyage.Controllers
{
    public class EvenementController : Controller
    {
        // GET: /<controller>/
        public IActionResult CreerEvenement()
        {

            return View();
          
        }

        [HttpPost]
        public IActionResult CreerEvenement(string Nom, DateTime Date, string Localisation, TypeEvenement TypeEvent)
        {
             
           
                using (Dal dal = new Dal())
                {
                    dal.CreerEvenement(Nom, Date, Localisation,TypeEvent);
                    return RedirectToAction("CreerEvenement");
                }
            
            
        }
<<<<<<< HEAD

        
        public IActionResult SupprimerEvenement(int id)

        {
            using (Dal dal = new Dal())
            {
                dal.SupprimerEvenement(id);
                return RedirectToAction("SupprimerEvenement");

            }
        }
    
=======
>>>>>>> f04a4c7b0412c7c5eef793eea701372a99a7dcf0
    }
}

Controllers/ServiceController.cs
using CodeVoyage.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Server.Kestrel.Core;
using System;

namespace CodeVoyage.Controllers
{
    public class ServiceController : Controller
    {
       public IActionResult CreerService()
        {
            return View();
        }

        //public IActionResult ModifierService(int id)
        //{
        //    if (id != 0)
        //    {
        //        using (Dal dal = new Dal())
        //        {
        //            Service service = dal.ObtientTousLesServices().Where(s => s.Id == id).FirstOrDefault();
        //            if (service == null)
        //            {
        //                return View("Error");
        //            }
        //            return View(service);
        //        }
        //    }
        //    return View("Error");
        //}
        [HttpPost]
        public IActionResult CreerService(string nomService, TypeService TypeService, int Capacite, DateTime DateDeb, DateTime DateFin, double Prix)
        {


            using (Dal dal = new Dal())
            {
                dal.CreerService(nomService, TypeService, Capacite,  DateDeb, DateFin, Prix);
                return RedirectToAction("CreerService");
            }


        }
        //public ActionResult Index()

        //{

        //    

        //    return View(entites.Services.ToList());

        //}

        [HttpPost]
        public IActionResult ModifierService(Service service)
        {

            if (!ModelState.IsValid)
                return View(service);

            if (service.Id != 0)
            {
                using (Dal dal = new Dal())
                {
                    dal.ModifierService(service);
                    return RedirectToAction("ModifierService", new { @id = service.Id });
                }
            }
            else
            {
                return View("Error");
            }
        }


        public IActionResult SupprimerService(int id)

        {
            using (Dal dal = new Dal())
            {
                dal.SupprimerService(id);
                return RedirectToAction("SupprimerService");

            }
        }
    }


}

Views/Service/CreerService.cshtml
@model CodeVoyage.Models.Service
@{
    ViewBag.Title = "Formulaire";
    Layout = "_LayoutDuSite";
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CréerService</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        <fieldset>
            <legend>Proposer un service: </legend>
            @Html.LabelFor(m => Model.nomService)
            @Html.TextBoxFor(m => Model.nomService)
            @*@Html.ValidationMessageFor(m => Model.Nom)*@
            <br />
            @Html.LabelFor(m => Model.TypeService)
            @Html.TextBoxFor(m => Model.TypeService)
            @*Html.ValidationMessageFor(m => Model.Telephone)*@
            <br />
            @Html.LabelFor(m => Model.Capacite)
            @Html.TextBoxFor(m => Model.Capacite)
            @*Html.ValidationMessageFor(m => Model.Telephone)*@
            <br />
            @Html.LabelFor(m => Model.DateDeb)
            @Html.TextBoxFor(m => Model.DateDeb, new { type = "date" })
            @*Html.ValidationMessageFor(m => Model.Telephone)*@
            <br />
            @Html.LabelFor(m => Model.DateFin)
            @Html.TextBoxFor(m => Model.DateFin, new { type = "date" })
            @*Html.ValidationMessageFor(m => Model.Telephone)*@
            <br />
            @Html.LabelFor(m => Model.Prix)
            @Html.TextBoxFor(m => Model.Prix)
            @*Html.ValidationMessageFor(m => Model.Telephone)*@
            <input type="submit" value="Ajouter" />
        </fieldset>
    }
</body>
@section Menu{
    <ul>
        <li>@Html.ActionLink("Accueil", "Index","Home")</li>
        <li class="selectionne>@Html.ActionLink("Ajout de service", "CreerService", "Service")</li>
        <li">@Html.ActionLink("Ajout d'Evenement", "CreerEvenement", "Evenement")</li>


    </ul>
}
</html>

Views/Service/ModifierService.cshtml
@model CodeVoyage.Models.Service
@{
    ViewBag.Title = "Formulaire";
    Layout = "_LayoutDuSite";
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ModifierService</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        <fieldset>
            <legend>Modifier un service: </legend>
            @Html.LabelFor(m => Model.nomService)
            @Html.TextBoxFor(m => Model.nomService)
            @Html.ValidationMessageFor(m => Model.nomService)
            <br />
            @Html.LabelFor(m => Model.TypeService)
            @Html.TextBoxFor(m => Model.TypeService)
            @Html.ValidationMessageFor(m => Model.TypeService)
            <br />
            @Html.LabelFor(m => Model.Capacite)
            @Html.TextBoxFor(m => Model.Capacite)
            @Html.ValidationMessageFor(m => Model.Capacite)
            <br />
            @Html.LabelFor(m => Model.DateDeb)
            @Html.TextBoxFor(m => Model.DateDeb, new { type = "date" })
            @Html.ValidationMessageFor(m => Model.DateDeb)
            <br />
            @Html.LabelFor(m => Model.DateFin)
            @Html.TextBoxFor(m => Model.DateFin, new { type = "date" })
            @Html.ValidationMessageFor(m => Model.DateFin)
            <br />
            @Html.LabelFor(m => Model.Prix)
            @Html.TextBoxFor(m => Model.Prix)
            @Html.ValidationMessageFor(m => Model.Prix)
            <input type="submit" value="Modifier" />
        </fieldset>

        
    }
    <script type="text/javascript" src="~/Scripts/jquery-3.3.1.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.validate-vsdoc.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.validate.unobtrusive.js"></script>
</body>
@section Menu{
    <ul>
        <li>@Html.ActionLink("Accueil", "Index","Home")</li>
        <li>@Html.ActionLink("Ajout de service", "CreerService", "Service")</li>
        <li class="selectionne">@Html.ActionLink("Modification de service", "ModifierService", "Service")</li>
    <li>@Html.ActionLink("Ajout d'Evenement", "CreerEvenement", "Evenement")</li>

    </ul>
}
</html>