Models/Itineraire.cs
using System;
namespace CodeVoyage.Models
{
	public class Itineraire
	{
        public int Id { get; set; }
        public string LieuDepart { get; set; }
        public string Destination { get; set; }
        public double Prix { get; set; }
        public MoyenDeTransport Transport { get; set; }
        public int NombreVoyageur { get; set; }
        public DateTime DateDepart { get; set; }
        public DateTime DateArrivee { get; set; }
    }
}

Controllers/ItineraireController.cs
using CodeVoyage.Models;
using Microsoft.AspNetCore.Mvc;
using System;

namespace CodeVoyage.Controllers
{
    public class ItineraireController : Controller
    {
        public IActionResult CreerItineraire()

        {
            return View();
        }

        [HttpPost]
        public IActionResult CreerItineraire(string LieuDepart, String Destination, double Prix, MoyenDeTransport Transport, int NombreVoyageur, DateTime DateDepart, DateTime DateArrivee)
        {


            using (Dal dal = new Dal())
            {
                dal.CreerItineraire(LieuDepart, Destination, Prix, Transport, NombreVoyageur, DateDepart, DateArrivee);


                return RedirectToAction("CreerItineraire");
            }






        }

        public IActionResult ObtientTousLesItineraires()

        {


            using (Dal dal = new Dal())
            {
                dal.ObtientTousLesItineraires();


                return RedirectToAction("ObtientTousLesItineraires");
            }


        }
    }
}

Views/Itineraire/CreerItineraire.cshtml
@model CodeVoyage.Models.Itineraire
@{
    ViewBag.Title = "Formulaire";
    Layout = "_LayoutDuSite";
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CréerItineraire</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        <fieldset>
            <legend>Créer un itinéraire: </legend>
            @Html.LabelFor(m => Model.LieuDepart)
            @Html.TextBoxFor(m => Model.LieuDepart)
            @*@Html.ValidationMessageFor(m => Model.LieuDepart)*@
            <br />
            @Html.LabelFor(m => Model.Destination)
            @Html.TextBoxFor(m => Model.Destination)
            @*Html.ValidationMessageFor(m => Model.Destination)*@
            <br />
            @Html.LabelFor(m => Model.Prix)
            @Html.TextBoxFor(m => Model.Prix)
            @*Html.ValidationMessageFor(m => Model.Prix)*@
            <br />
            @Html.LabelFor(m => Model.Transport)
            @Html.DropDownListFor(m => m.Transport, Html.GetEnumSelectList<CodeVoyage.Models.MoyenDeTransport>(), "Selectionner un transport")
          
            @*Html.ValidationMessageFor(m => Model.Transport)*@
            <br/>
            @Html.LabelFor(m => Model.NombreVoyageur)
            @Html.TextBoxFor(m => Model.NombreVoyageur)
            @*Html.ValidationMessageFor(m => Model.NombreVoyageur)*@
            <br />
            @Html.LabelFor(m => Model.DateDepart )
            @Html.TextBoxFor(m => Model.DateDepart, new { type="date"})
            @*Html.ValidationMessageFor(m => Model.DateDepart)*@
            <br />
            @Html.LabelFor(m => Model.DateArrivee)
            @Html.TextBoxFor(m => Model.DateArrivee , new { type="date"})
            @*Html.ValidationMessageFor(m => Model.DateArrivee)*@
            <br />

            <input type="submit" value="Ajouter" />
        </fieldset>
    }
</body>
@section Menu{
    <ul>
        <li>@Html.ActionLink("Accueil", "Index","Home")</li>
        <li class="selectionne">@Html.ActionLink("Ajout d'itineraire", "CreerItineraire", "Itineraire")</li>


    </ul>
}
</html>